apiVersion: apps/v1
kind: Deployment
metadata:
 name: python-app
 labels:
   app: python-app
spec:
 replicas: 1
 selector:
   matchLabels:
     app: python-app
 template:
   metadata:
     labels:
       app: python-app
   spec:
     containers:
       - name: python-app-hello-world
         image: asia-south1-docker.pkg.dev/river-blade-408018/linu-artifact-repo/python-app:dd6fe38

         imagePullPolicy: Always
         ports:
           - containerPort: 8080
         readinessProbe:
           httpGet:
             path: /
             port: 8080
           initialDelaySeconds: 5
           timeoutSeconds: 5
           periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: python-app

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app-ingress
  annotations:
      kubernetes.io/ingress.global-static-ip-name: session-static-ip
spec:
  rules:
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-app-service
                port:
                  number: 8080
