The workflow is not valid. .github/workflows/github-actions-merge.yaml (Line: 74, Col: 1): Unexpected value 'workflows'
name: Deploy to GKE and Push to Artifact Registry

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure GCP environment
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - run: |-
          gcloud --quiet auth configure-docker asia-south1-docker.pkg.dev

      - name: Set outputs
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --tag "asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-artifact-repo/python-app:${{ env.SHA_SHORT }}" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push "asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-artifact-repo/python-app:${{ env.SHA_SHORT }}"

  deploy-to-gke:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to GKE
        uses: google-github-actions/auth-gke@v0.4.0
        with:
          cluster_name: gke-cluster
          location: asia-south1-a
          project_id: river-blade-408018
          service_account_key: ${{ secrets.GKE_SA_KEY }}

      - name: Update Kubernetes Deployment
        run: |
          echo "Updating Kubernetes Deployment..."

          sed -i "s#asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-artifact-repo/python-app:.*#asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-artifact-repo/python-app:${{ env.SHA_SHORT }}#" .github/deploy/deployment.yaml
          kubectl apply -f .github/deploy/deployment.yaml -n linu-ns
          echo "Issuing rollout restart..."
          kubectl rollout restart deploy python-app -n linu-ns

      - name: Commit and Push Updated Deployment File
        run: |
          git add .github/deploy/deployment.yaml
          git -c user.email="linujose23@gmail.com" -c user.name="linujose23" \
              commit -m "Update Docker image tag in deployment.yaml [skip ci]"
          git push origin ${{ github.ref }} --quiet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
